language: ruby
rvm:
- 1.9.3
env:
  global:
    - secure: "codDCIg6hzovKc+EPTEJ6QlWFxxfKrZv6ATIqnNzyjxvGwPVPcN7Rr0PMdZeJg8APJ/Hk+BsAKWmyhqa3LbR/U3yR0Npl+w6K2IisKoshRrCb4KIJbh4QS53CHsn8d9g6YFXLbN5OQacuPaStGJGUUyJ3dfizfN1pCr6rtpX8A8="
before_install:
- gem install cucumber
- gem install rspec
script:
- cucumber install/install.feature
- cucumber features
