language: ruby
rvm:
  - "1.9.3"
before_install:
# works with default latest 2.2.2 as of 2014/3/11
#  - gem update --system 2.2.0
#  - gem --version
  - gem install cucumber
  - gem install rspec
script:
  - cucumber install/install.feature
  - cucumber features